cat: 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_.ext: No such file or directory
Solving the KS system of order  27  with  1839348  constraints
351 variables will be considered for cubing
2024-02-20 23:47:42 gra226 MCTS[12878] WARNING NO EXPLORATION!!!!
Time taken for cubing:  12.37
2024-02-20 23:47:43 gra226 Coach[12878] INFO 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_1.cubes already exists. Replacing old file!
2024-02-20 23:47:43 gra226 Coach[12878] INFO Saved cubes to file
Reward:  0.020874620161183775
Tool runtime:  33.902
Solving the KS system of order  27  with  974369  constraints
351 variables will be considered for cubing
2024-02-20 23:49:19 gra226 MCTS[31163] WARNING NO EXPLORATION!!!!
Time taken for cubing:  6.242
2024-02-20 23:49:19 gra226 Coach[31163] INFO 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_10.cubes already exists. Replacing old file!
2024-02-20 23:49:19 gra226 Coach[31163] INFO Saved cubes to file
Reward:  0.007266481701677896
Tool runtime:  15.007
Solving the KS system of order  27  with  1681027  constraints
351 variables will be considered for cubing
Solving the KS system of order  27  with  453380  constraints
351 variables will be considered for cubing
2024-02-20 23:50:19 gra226 MCTS[3235] WARNING NO EXPLORATION!!!!
Time taken for cubing:  13.092
2024-02-20 23:50:19 gra226 Coach[3235] INFO 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_100.cubes already exists. Replacing old file!
2024-02-20 23:50:19 gra226 Coach[3235] INFO Saved cubes to file
Reward:  0.05469018364381028
Tool runtime:  17.37
/bin/sh: 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_1000: Disk quota exceeded
/bin/sh: 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_1001: Disk quota exceeded
2024-02-20 23:50:23 gra226 MCTS[31962] WARNING NO EXPLORATION!!!!
Time taken for cubing:  53.217
2024-02-20 23:50:23 gra226 Coach[31962] INFO 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_11.cubes already exists. Replacing old file!
2024-02-20 23:50:23 gra226 Coach[31962] INFO Saved cubes to file
Reward:  0.010965781477077554
Tool runtime:  69.237
/bin/sh: 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_110: Disk quota exceeded
Process Process-31:
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.10.2/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.10.2/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/scratch/c4duggan/R4_latest/MathCheckRamsey/parallel-solve.py", line 66, in worker
    run_cube_command(args)
  File "/scratch/c4duggan/R4_latest/MathCheckRamsey/parallel-solve.py", line 31, in run_cube_command
    eval(command)
  File "<string>", line 1, in <module>
  File "/scratch/c4duggan/R4_latest/MathCheckRamsey/parallel-solve.py", line 98, in cube
    os.rename(f"{file_to_cube}.simp", rename_file(file_to_cube))
FileNotFoundError: [Errno 2] No such file or directory: '27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_101.simp' -> '27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_101'
Process 26038: Executing command: ./solve-verify.sh 27 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_100
solved
Removed: 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_100
Removed: 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_100.perm
Error: No such file or directory. File: 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_100.nonembed
Removed: 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_100.drat
cube('27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_101', 351, '27', 2, queue, 'd', 5, 2, 113)
./simplification/simplify-by-conflicts.sh -s 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_101 27 10000 | tee 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_101.simplog
120 variables removed from the cube
Process Process-12:
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.10.2/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.10.2/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/scratch/c4duggan/R4_latest/MathCheckRamsey/parallel-solve.py", line 66, in worker
    run_cube_command(args)
  File "/scratch/c4duggan/R4_latest/MathCheckRamsey/parallel-solve.py", line 31, in run_cube_command
    eval(command)
  File "<string>", line 1, in <module>
  File "/scratch/c4duggan/R4_latest/MathCheckRamsey/parallel-solve.py", line 98, in cube
    os.rename(f"{file_to_cube}.simp", rename_file(file_to_cube))
FileNotFoundError: [Errno 2] No such file or directory: '27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_111.simp' -> '27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_111'
Process 26019: Executing command: ./solve-verify.sh 27 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_111101
solved
Removed: 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_111101
Removed: 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_111101.perm
Error: No such file or directory. File: 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_111101.nonembed
Removed: 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_111101.drat
cube('27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_111', 351, '27', 2, queue, 'd', 5, 2, 60)
./simplification/simplify-by-conflicts.sh -s 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_111 27 10000 | tee 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_111.simplog
65 variables removed from the cube
Process Process-23:
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.10.2/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.10.2/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/scratch/c4duggan/R4_latest/MathCheckRamsey/parallel-solve.py", line 66, in worker
    run_cube_command(args)
  File "/scratch/c4duggan/R4_latest/MathCheckRamsey/parallel-solve.py", line 31, in run_cube_command
    eval(command)
  File "<string>", line 1, in <module>
  File "/scratch/c4duggan/R4_latest/MathCheckRamsey/parallel-solve.py", line 98, in cube
    os.rename(f"{file_to_cube}.simp", rename_file(file_to_cube))
FileNotFoundError: [Errno 2] No such file or directory: '27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_111000.simp' -> '27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_111000'
Process 26030: Executing command: ./solve-verify.sh 27 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_111010
solved
Removed: 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_111010
Removed: 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_111010.perm
Error: No such file or directory. File: 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_111010.nonembed
Removed: 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_111010.drat
cube('27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_111000', 351, '27', 2, queue, 'd', 5, 0)
./simplification/simplify-by-conflicts.sh -s 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_111000 27 10000 | tee 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_111000.simplog
96 variables removed from the cube
Process Process-3:
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.10.2/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.10.2/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/scratch/c4duggan/R4_latest/MathCheckRamsey/parallel-solve.py", line 66, in worker
    run_cube_command(args)
  File "/scratch/c4duggan/R4_latest/MathCheckRamsey/parallel-solve.py", line 31, in run_cube_command
    eval(command)
  File "<string>", line 1, in <module>
  File "/scratch/c4duggan/R4_latest/MathCheckRamsey/parallel-solve.py", line 98, in cube
    os.rename(f"{file_to_cube}.simp", rename_file(file_to_cube))
FileNotFoundError: [Errno 2] No such file or directory: '27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_10110.simp' -> '27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_10110'
Process 26010: Executing command: ./solve-verify.sh 27 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_1
Continue cubing this subproblem...
cube('27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_10110', 351, '27', 2, queue, 'd', 5, 0)
./simplification/simplify-by-conflicts.sh -s 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_10110 27 10000 | tee 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_10110.simplog
137 variables removed from the cube
Process Process-2:
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.10.2/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.10.2/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/scratch/c4duggan/R4_latest/MathCheckRamsey/parallel-solve.py", line 66, in worker
    run_cube_command(args)
  File "/scratch/c4duggan/R4_latest/MathCheckRamsey/parallel-solve.py", line 31, in run_cube_command
    eval(command)
  File "<string>", line 1, in <module>
  File "/scratch/c4duggan/R4_latest/MathCheckRamsey/parallel-solve.py", line 98, in cube
    os.rename(f"{file_to_cube}.simp", rename_file(file_to_cube))
FileNotFoundError: [Errno 2] No such file or directory: '27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_1011.simp' -> '27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_1011'
Process 26009: Executing command: ./solve-verify.sh 27 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_100101
solved
Removed: 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_100101
Removed: 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_100101.perm
Error: No such file or directory. File: 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_100101.nonembed
Removed: 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_100101.drat
cube('27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_1', 351, '27', 2, queue, 'd', 5, 0)
./simplification/simplify-by-conflicts.sh -s 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_1 27 10000 | tee 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_1.simplog
49 variables removed from the cube
cube('27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_1011', 351, '27', 2, queue, 'd', 5, 0)
./simplification/simplify-by-conflicts.sh -s 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_1011 27 10000 | tee 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_1011.simplog
124 variables removed from the cube
Process Process-29:
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.10.2/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.10.2/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/scratch/c4duggan/R4_latest/MathCheckRamsey/parallel-solve.py", line 66, in worker
    run_cube_command(args)
  File "/scratch/c4duggan/R4_latest/MathCheckRamsey/parallel-solve.py", line 31, in run_cube_command
    eval(command)
  File "<string>", line 1, in <module>
  File "/scratch/c4duggan/R4_latest/MathCheckRamsey/parallel-solve.py", line 98, in cube
    os.rename(f"{file_to_cube}.simp", rename_file(file_to_cube))
FileNotFoundError: [Errno 2] No such file or directory: '27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_10.simp' -> '27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_10'
Process 26036: Executing command: ./solve-verify.sh 27 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_1001
solved
Removed: 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_1001
Removed: 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_1001.perm
Error: No such file or directory. File: 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_1001.nonembed
Removed: 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_1001.drat
cube('27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_100', 351, '27', 2, queue, 'd', 5, 2, 113)
./simplification/simplify-by-conflicts.sh -s 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_100 27 10000 | tee 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_100.simplog
150 variables removed from the cube
cube('27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_10', 351, '27', 2, queue, 'd', 5, 0)
./simplification/simplify-by-conflicts.sh -s 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_10 27 10000 | tee 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_10.simplog
117 variables removed from the cube
Process Process-21:
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.10.2/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.10.2/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/scratch/c4duggan/R4_latest/MathCheckRamsey/parallel-solve.py", line 66, in worker
    run_cube_command(args)
  File "/scratch/c4duggan/R4_latest/MathCheckRamsey/parallel-solve.py", line 31, in run_cube_command
    eval(command)
  File "<string>", line 1, in <module>
  File "/scratch/c4duggan/R4_latest/MathCheckRamsey/parallel-solve.py", line 98, in cube
    os.rename(f"{file_to_cube}.simp", rename_file(file_to_cube))
FileNotFoundError: [Errno 2] No such file or directory: '27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_101100.simp' -> '27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_101100'
Process 26028: Executing command: ./solve-verify.sh 27 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_10101
solved
Removed: 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_10101
Removed: 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_10101.perm
Error: No such file or directory. File: 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_10101.nonembed
Removed: 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_10101.drat
cube('27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_11', 351, '27', 2, queue, 'd', 5, 1, 49)
./simplification/simplify-by-conflicts.sh -s 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_11 27 10000 | tee 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_11.simplog
60 variables removed from the cube
cube('27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_101100', 351, '27', 2, queue, 'd', 5, 0)
./simplification/simplify-by-conflicts.sh -s 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_101100 27 10000 | tee 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_101100.simplog
143 variables removed from the cube
Process Process-28:
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.10.2/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.10.2/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/scratch/c4duggan/R4_latest/MathCheckRamsey/parallel-solve.py", line 66, in worker
    run_cube_command(args)
  File "/scratch/c4duggan/R4_latest/MathCheckRamsey/parallel-solve.py", line 31, in run_cube_command
    eval(command)
  File "<string>", line 1, in <module>
  File "/scratch/c4duggan/R4_latest/MathCheckRamsey/parallel-solve.py", line 98, in cube
    os.rename(f"{file_to_cube}.simp", rename_file(file_to_cube))
FileNotFoundError: [Errno 2] No such file or directory: '27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_10111.simp' -> '27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_10111'
Process 26035: Executing command: ./solve-verify.sh 27 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_111000
Continue cubing this subproblem...
cube('27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_10111', 351, '27', 2, queue, 'd', 5, 0)
./simplification/simplify-by-conflicts.sh -s 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_10111 27 10000 | tee 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_10111.simplog
127 variables removed from the cube
Process Process-18:
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.10.2/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.10.2/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/scratch/c4duggan/R4_latest/MathCheckRamsey/parallel-solve.py", line 66, in worker
    run_cube_command(args)
  File "/scratch/c4duggan/R4_latest/MathCheckRamsey/parallel-solve.py", line 31, in run_cube_command
    eval(command)
  File "<string>", line 1, in <module>
  File "/scratch/c4duggan/R4_latest/MathCheckRamsey/parallel-solve.py", line 98, in cube
    os.rename(f"{file_to_cube}.simp", rename_file(file_to_cube))
FileNotFoundError: [Errno 2] No such file or directory: '27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_101111.simp' -> '27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_101111'
Process 26025: Executing command: ./solve-verify.sh 27 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_10110
Continue cubing this subproblem...
cube('27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_101111', 351, '27', 2, queue, 'd', 5, 0)
./simplification/simplify-by-conflicts.sh -s 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_101111 27 10000 | tee 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_101111.simplog
128 variables removed from the cube
Process Process-10:
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.10.2/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.10.2/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/scratch/c4duggan/R4_latest/MathCheckRamsey/parallel-solve.py", line 66, in worker
    run_cube_command(args)
  File "/scratch/c4duggan/R4_latest/MathCheckRamsey/parallel-solve.py", line 31, in run_cube_command
    eval(command)
  File "<string>", line 1, in <module>
  File "/scratch/c4duggan/R4_latest/MathCheckRamsey/parallel-solve.py", line 98, in cube
    os.rename(f"{file_to_cube}.simp", rename_file(file_to_cube))
FileNotFoundError: [Errno 2] No such file or directory: '27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_11100.simp' -> '27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_11100'
Process 26017: Executing command: ./solve-verify.sh 27 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_111
Continue cubing this subproblem...
cube('27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_11100', 351, '27', 2, queue, 'd', 5, 0)
./simplification/simplify-by-conflicts.sh -s 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_11100 27 10000 | tee 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_11100.simplog
84 variables removed from the cube
Process Process-22:
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.10.2/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.10.2/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/scratch/c4duggan/R4_latest/MathCheckRamsey/parallel-solve.py", line 66, in worker
    run_cube_command(args)
  File "/scratch/c4duggan/R4_latest/MathCheckRamsey/parallel-solve.py", line 31, in run_cube_command
    eval(command)
  File "<string>", line 1, in <module>
  File "/scratch/c4duggan/R4_latest/MathCheckRamsey/parallel-solve.py", line 98, in cube
    os.rename(f"{file_to_cube}.simp", rename_file(file_to_cube))
FileNotFoundError: [Errno 2] No such file or directory: '27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_101101.simp' -> '27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_101101'
Process 26029: Executing command: ./solve-verify.sh 27 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_10
Continue cubing this subproblem...
cube('27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_101101', 351, '27', 2, queue, 'd', 5, 0)
./simplification/simplify-by-conflicts.sh -s 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_101101 27 10000 | tee 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_101101.simplog
149 variables removed from the cube
Process Process-26:
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.10.2/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.10.2/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/scratch/c4duggan/R4_latest/MathCheckRamsey/parallel-solve.py", line 66, in worker
    run_cube_command(args)
  File "/scratch/c4duggan/R4_latest/MathCheckRamsey/parallel-solve.py", line 31, in run_cube_command
    eval(command)
  File "<string>", line 1, in <module>
  File "/scratch/c4duggan/R4_latest/MathCheckRamsey/parallel-solve.py", line 98, in cube
    os.rename(f"{file_to_cube}.simp", rename_file(file_to_cube))
FileNotFoundError: [Errno 2] No such file or directory: '27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_1110.simp' -> '27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_1110'
Process 26033: Executing command: ./solve-verify.sh 27 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_101100
Continue cubing this subproblem...
cube('27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_1110', 351, '27', 2, queue, 'd', 5, 0)
./simplification/simplify-by-conflicts.sh -s 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_1110 27 10000 | tee 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_1110.simplog
71 variables removed from the cube
Process Process-30:
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.10.2/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.10.2/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/scratch/c4duggan/R4_latest/MathCheckRamsey/parallel-solve.py", line 66, in worker
    run_cube_command(args)
  File "/scratch/c4duggan/R4_latest/MathCheckRamsey/parallel-solve.py", line 31, in run_cube_command
    eval(command)
  File "<string>", line 1, in <module>
  File "/scratch/c4duggan/R4_latest/MathCheckRamsey/parallel-solve.py", line 98, in cube
    os.rename(f"{file_to_cube}.simp", rename_file(file_to_cube))
FileNotFoundError: [Errno 2] No such file or directory: '27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_11.simp' -> '27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_11'
Process 26037: Executing command: ./solve-verify.sh 27 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_10111
Continue cubing this subproblem...
cube('27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_11', 351, '27', 2, queue, 'd', 5, 0)
./simplification/simplify-by-conflicts.sh -s 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_11 27 10000 | tee 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_11.simplog
65 variables removed from the cube
Process Process-13:
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.10.2/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.10.2/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/scratch/c4duggan/R4_latest/MathCheckRamsey/parallel-solve.py", line 66, in worker
    run_cube_command(args)
  File "/scratch/c4duggan/R4_latest/MathCheckRamsey/parallel-solve.py", line 31, in run_cube_command
    eval(command)
  File "<string>", line 1, in <module>
  File "/scratch/c4duggan/R4_latest/MathCheckRamsey/parallel-solve.py", line 98, in cube
    os.rename(f"{file_to_cube}.simp", rename_file(file_to_cube))
FileNotFoundError: [Errno 2] No such file or directory: '27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_111001.simp' -> '27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_111001'
Process 26020: Executing command: ./solve-verify.sh 27 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_101111
Continue cubing this subproblem...
cube('27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_111001', 351, '27', 2, queue, 'd', 5, 0)
./simplification/simplify-by-conflicts.sh -s 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_111001 27 10000 | tee 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_111001.simplog
90 variables removed from the cube
Process Process-16:
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.10.2/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.10.2/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/scratch/c4duggan/R4_latest/MathCheckRamsey/parallel-solve.py", line 66, in worker
    run_cube_command(args)
  File "/scratch/c4duggan/R4_latest/MathCheckRamsey/parallel-solve.py", line 31, in run_cube_command
    eval(command)
  File "<string>", line 1, in <module>
  File "/scratch/c4duggan/R4_latest/MathCheckRamsey/parallel-solve.py", line 98, in cube
    os.rename(f"{file_to_cube}.simp", rename_file(file_to_cube))
FileNotFoundError: [Errno 2] No such file or directory: '27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_11101.simp' -> '27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_11101'
Process 26023: Executing command: ./solve-verify.sh 27 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_101
Continue cubing this subproblem...
cube('27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_11101', 351, '27', 2, queue, 'd', 5, 0)
./simplification/simplify-by-conflicts.sh -s 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_11101 27 10000 | tee 27_3_8_4_7_0_0_0_100000_2_d_5_1_l/constraints_27_3_8_4_7_0_0_0_100000_2_d_5_11101.simplog
87 variables removed from the cube
slurmstepd: error: *** JOB 17110587 ON gra226 CANCELLED AT 2024-02-23T12:55:06 ***
